sequenceDiagram
    autonumber
    actor U as 用户
    participant M as 主界面
    participant P as 求购信息发布页面
    participant D as DAO
    participant DB as 数据库

    U->>M: 用户进入系统
    activate M
    
    M->>P: 求购信息发布
    activate P
    
    P->>D: 提交推荐请求
    activate D
    
    D->>DB: 查询所有满足条件项目
    activate DB
    
    DB-->>D: 返回查询信息
    deactivate DB
    
    D-->>P: 返回查询结果
    deactivate D
    
    P-->>M: 显示推荐信息
    deactivate P
    
    deactivate M
