export const FEEDBACK_AUTH_ERROR_CODE = {
  SMS_INVALID_OR_EXPIRED: "AUTH_SMS_INVALID_OR_EXPIRED",
  PHONE_INVALID: "AUTH_PHONE_INVALID",
  PHONE_REQUIRED: "AUTH_PHONE_REQUIRED",
  CODE_REQUIRED: "AUTH_CODE_REQUIRED",
  LOGIN_EXPIRED: "AUTH_LOGIN_EXPIRED",
  TOO_FREQUENT: "AUTH_TOO_FREQUENT",
  PASSWORD_WRONG: "AUTH_PASSWORD_WRONG",
  ACCOUNT_NOT_EXIST: "AUTH_ACCOUNT_NOT_EXIST",
  PHONE_ALREADY_REGISTERED: "AUTH_PHONE_ALREADY_REGISTERED",
  CAPTCHA_INVALID: "AUTH_CAPTCHA_INVALID",
  CAPTCHA_EXPIRED: "AUTH_CAPTCHA_EXPIRED",
  PASSWORD_TOO_SHORT: "AUTH_PASSWORD_TOO_SHORT",
  UNKNOWN: "AUTH_UNKNOWN"
};
